spring.application.name=backend
server.port=8080

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.zmvcvttzalkisomhguxh
spring.datasource.password=dw4FqjKu712vy4fL
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT configuration
# jwt.secret=MySuperSecretKeyThatIsAtLeast32CharactersLong123456789
# jwt.expiration=86400000

# # Admin seeding
# admin.email=admin@eventwear.com
# admin.temp-password=Admin@123